### ISSUE TITLE
Can't download pretrained model and dataset

### ISSUE THREAD

**Issue by xevolesi** [vlkniaz/ThermalGAN#1]
Hi. How can i download your dataset and pretrained model?

**Comment by lchunleo** [comment]
same query, is there any update on this? thank you

**Comment by bjajoh** [comment]
http://zefirus.org/datasets/models/ThermalGAN/ThermalGAN.pth

**Comment by xevolesi** [comment]
> http://zefirus.org/datasets/models/ThermalGAN/ThermalGAN.pth

Thanks. I was able to download weights!

**Comment by PrashantDixit0** [comment]
This link is still showing Page not Found.

**Comment by Maxlium** [comment]
> http://zefirus.org/datasets/models/ThermalGAN/ThermalGAN.pth

sorry, the page is not found.Can you share the pre-train model?

**Comment by legendary111** [comment]
@xevolesi Hi,could you provide the  pre-trained model? This link is still showing Page not Found.

**Comment by WeiBrown** [comment]
> > http://zefirus.org/datasets/models/ThermalGAN/ThermalGAN.pth
> 
> Thanks. I was able to download weights!

hi. sorry to bother you, the weight is not avalible in this link, can i get the weight you downloaded? my email is ve159334759111@gmail.com  thanks a lot

**Comment by WeiBrown** [comment]
@xevolesi  hi. sorry to bother you, the weight is not avalible in this link, can i get the weight you downloaded? my email is [ve159334759111@gmail.com](mailto:ve159334759111@gmail.com) thanks a lot

**Comment by 001asdasda** [comment]
@xevolesi hi. sorry to bother you, the weight is not avalible in this link, can i get the weight you downloaded? my email is [bohuang735@gmail.com](mailto:bohuang735@gmail.com) thanks a lot

**Comment by 001asdasda** [comment]
@WeiBrown Hello, I'm in need of the ThermalGAN.pth weights for a research project and was wondering if you might be able to share them with me. If you have the file and are willing to share, could you please send it to bohuang735@gmail.com?

**Comment by 001asdasda** [comment]
@legendary111 Hello, I'm in need of the ThermalGAN.pth weights for a research project and was wondering if you might be able to share them with me. If you have the file and are willing to share, could you please send it to bohuang735@gmail.com?

**Comment by 001asdasda** [comment]
@Maxlium Hello, I'm in need of the ThermalGAN.pth weights for a research project and was wondering if you might be able to share them with me. If you have the file and are willing to share, could you please send it to bohuang735@gmail.com?

**Comment by 001asdasda** [comment]
@xevolesi Hello, I'm in need of the ThermalGAN.pth weights for a research project and was wondering if you might be able to share them with me. If you have the file and are willing to share, could you please send it to bohuang735@gmail.com?

**Comment by xevolesi** [comment]
Hello guys!  People often email me asking for pretrained weights. I can't share downloaded weights with you, because i downloaded it almost 6 years ago. I downloaded this weights to computing server at my previous job and now i DON'T have an access to this server and i DONT have any copy of this weights on my personal computer or file storage. I don't mind sharing pretrained weights with you, but I don't have them. Pretrained weights were left on the computing server at my previous job.

**Comment by Sherlock1011** [comment]
> http://zefirus.org/datasets/models/ThermalGAN/ThermalGAN.pth

hi Sir，could you share the link again？This link unwork,thank you

**Comment by LiaoZihZrong** [comment]
Hi, ALL
i find the pretrain model,
3 years ago, i have download in my PC,
and i found it,
https://drive.google.com/drive/folders/1mv4AhvMjoRMdSkDDbXp95CgA24tkefqH?usp=sharing
(this zip have some my file, please skip or del it )

**Comment by LiaoZihZrong** [comment]
> > http://zefirus.org/datasets/models/ThermalGAN/ThermalGAN.pth
> 
> hi Sir，could you share the link again？This link unwork,thank you

https://drive.google.com/drive/folders/1mv4AhvMjoRMdSkDDbXp95CgA24tkefqH?usp=sharing
(this zip have some my file, please skip or del it )

**Comment by sakoXY** [comment]
@LiaoZihZrong Hi,  can you tell me the composition of your test dataset? Especially _IR_32_, _LABEL_TEMP_, _PW3D_, _TV_, what do these folders mean respectively?
