### ISSUE TITLE
the model is not available

### ISSUE THREAD

**Issue by xingchenzhang** [vlkniaz/ThermalGAN#4]
Hi,

For some reason, I cannot download the model. Could you please tell me how to handle this?

Regards,
Chen

**Comment by bjajoh** [comment]
http://zefirus.org/datasets/models/ThermalGAN/ThermalGAN.pth

**Comment by desertnaut** [comment]
Please see also https://github.com/vlkniaz/ThermalGAN/issues/1 (which repeats the solution above), and then close this issue.

**Comment by LiaoZihZrong** [comment]
> Hi,
> 
> For some reason, I cannot download the model. Could you please tell me how to handle this?
> 
> Regards, Chen

https://github.com/vlkniaz/ThermalGAN/issues/1#issuecomment-2381939457
